language: php
php:
  - 5.5
  - 5.4
  - 5.3
  
before_script:
  - composer require --no-update satooshi/php-coveralls '~1.0'
  - composer update --no-interaction

script:
  - mkdir -p build/logs
  - phpunit --bootstrap src/MetarDecoder.inc.php --coverage-clover build/logs/clover.xml tests

after_script:
  - php vendor/bin/coveralls
  
sudo: false
